.github/workflows/docker-build-push.ymlname: Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/Login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build & push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .github/workflows/docker-build-push.yml
          push: true
          tags: |
              ${{ vars.DOCKERHUB_USER }}/github-actions-app:${{ github.ref_name }}
              ${{ vars.DOCKERHUB_USER }}/github-actions-app:latest
              ${{ vars.DOCKERHUB_USER }}/github-actions-app:${{ github.sha }}

              
              
                      
          

       
