# This is the workflow name
name: Hello Workflow

# Runs on an automatic trigger whenever a change is pushed to the branch[deployment]
on:
  push:
    branches: [main] 
    
# These are jobs inside the workflow
jobs:
   
  # This is the name of the job
  greet:
    # This is a GitHub runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"
        
  details:
     runs-on: ubuntu-latest
     steps:
       - name: show that is the version of python, docker, etc
         run: docker --version && python --version
         
